### ISSUE TITLE
How can I replace outliers in columns with IQR rule?

### ISSUE THREAD

**Issue by peeush-agarwal** [sid-the-coder/QuickDA#1]
I'd like not to remove rows with outliers which this method performed:  
`df = clean(df, method='outliers') # Reduced rows from x to x-40`

But instead of removing rows with outlier values in columns, I'd like to replace outlier values with IQR rule. Do we have support for that currently?

Thanks in advance

**Comment by sid-the-coder** [comment]
Peeush,

Yes, there is a way in which you can remove outliers based on column(s)!

`clean(data, method="outliers", columns=[])`
**** Returns Pandas DataFrame**

Given a DataFrame data, it removes outliers for all column(s) specified as string/list in columns.  

I have written a medium article explaining each method in detail. Do let me know if this helps you!
https://medium.com/@gauty95/quickda-low-code-python-library-for-quick-exploratory-data-analysis-b4b1c3af369d

Thank you for using the library!
